-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.department
(
    dept_id integer NOT NULL DEFAULT nextval('department_dept_id_seq'::regclass),
    dept_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT department_pkey PRIMARY KEY (dept_id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    id integer NOT NULL DEFAULT nextval('employee_id_seq'::regclass),
    email character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    roles character varying(255) COLLATE pg_catalog."default",
    dept_id_fk integer,
    CONSTRAINT employee_pkey PRIMARY KEY (id),
    CONSTRAINT uk_fopic1oh5oln2khj8eat6ino0 UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.employee_details
(
    emp_md_id integer NOT NULL DEFAULT nextval('employee_details_emp_md_id_seq'::regclass),
    contact_details character varying(255) COLLATE pg_catalog."default",
    date_of_birth timestamp(6) without time zone,
    designation character varying(255) COLLATE pg_catalog."default",
    gender character varying(255) COLLATE pg_catalog."default",
    joining_date timestamp(6) without time zone,
    salary integer,
    emp_id_fk integer,
    CONSTRAINT employee_details_pkey PRIMARY KEY (emp_md_id)
);

CREATE TABLE IF NOT EXISTS public.employee_project
(
    project_id integer NOT NULL,
    employee_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.employee_report
(
    report_id integer NOT NULL DEFAULT nextval('employee_report_report_id_seq'::regclass),
    report_status character varying(255) COLLATE pg_catalog."default",
    reporting_date character varying(255) COLLATE pg_catalog."default",
    work_done character varying(255) COLLATE pg_catalog."default",
    emp_id_fk integer,
    feedback_id_fk integer,
    CONSTRAINT employee_report_pkey PRIMARY KEY (report_id)
);

CREATE TABLE IF NOT EXISTS public.mentor
(
    mentor_id integer NOT NULL,
    emp_id_fk integer,
    CONSTRAINT mentor_pkey PRIMARY KEY (mentor_id)
);

CREATE TABLE IF NOT EXISTS public.mentor_feedback
(
    feedback_id integer NOT NULL DEFAULT nextval('mentor_feedback_feedback_id_seq'::regclass),
    feedback character varying(255) COLLATE pg_catalog."default",
    flag boolean,
    rating character varying(255) COLLATE pg_catalog."default",
    mentor_id_fk integer,
    CONSTRAINT mentor_feedback_pkey PRIMARY KEY (feedback_id)
);

CREATE TABLE IF NOT EXISTS public.project
(
    project_id integer NOT NULL,
    project_desc character varying(255) COLLATE pg_catalog."default",
    project_name character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT project_pkey PRIMARY KEY (project_id)
);

ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT fkbthmgcnfim4er4c5op0ucjny0 FOREIGN KEY (dept_id_fk)
    REFERENCES public.department (dept_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_details
    ADD CONSTRAINT fkav55htofl5v6pxxxe8bjxifen FOREIGN KEY (emp_id_fk)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_project
    ADD CONSTRAINT fk4yddvnm7283a40plkcti66wv9 FOREIGN KEY (project_id)
    REFERENCES public.project (project_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_project
    ADD CONSTRAINT fkb25s5hgggo6k4au4sye7teb3a FOREIGN KEY (employee_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_report
    ADD CONSTRAINT fk611n7ew2m4pg5saj4ae01tdby FOREIGN KEY (emp_id_fk)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee_report
    ADD CONSTRAINT fkf0tabagxrs9qngev2p09js6pd FOREIGN KEY (feedback_id_fk)
    REFERENCES public.mentor_feedback (feedback_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mentor
    ADD CONSTRAINT fke0k7q10jvf4fvh0vvadb5ndac FOREIGN KEY (emp_id_fk)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mentor_feedback
    ADD CONSTRAINT fkhvlaihr2ku7x78aq0g91pews4 FOREIGN KEY (mentor_id_fk)
    REFERENCES public.mentor (mentor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;